---
################
# Build & Test #
################

kind: pipeline
name: run_tests

platform:
  arch: amd64
  os: linux

steps:
  - name: backend
    image: golang
    commands:
      - echo "backend testing"

  - name: test
    image: python:3.4
    commands:
      - echo $(which python)
      - python -m unittest discover

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      username: adam.chen
      template: >
        build {{build.number}} succeeded. Good job.
    when:
      status: [ success, failure ]

  - name: deploy
    image: alpine
    commands:
      - echo "deploy"
    when:
      status: [ success ]
